services:
  ai-prescription-reader:
    build:
      context: .
    image: prajwalhk152/ai-prescription-reader:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
